/*
 * @(#)Interface.java	1.4 04/01/27
 *
 * Copyright (c) 2004 Sun Microsystems, Inc. All rights reserved. 
 * PROPRIETARY/CONFIDENTIAL
 * Use is subject to license terms
 */// This class was generated by 172 StubGenerator.
// Contents subject to change without notice.
// @generated

package example.serverscript.connector;

public interface Interface extends java.rmi.Remote {
	public java.lang.String request(java.lang.String string_1, java.lang.String string_2) throws java.rmi.RemoteException;

}
