/*
 * @(#)Request.java	1.4 04/01/27
 *
 * Copyright (c) 2004 Sun Microsystems, Inc. All rights reserved. 
 * PROPRIETARY/CONFIDENTIAL
 * Use is subject to license terms
 */// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build EA-R39)

package example.serverscript.connector;


public class Request {
    protected java.lang.String string_1;
    protected java.lang.String string_2;
    
    public Request() {
    }
    
    public Request(java.lang.String string_1, java.lang.String string_2) {
        this.string_1 = string_1;
        this.string_2 = string_2;
    }
    
    public java.lang.String getString_1() {
        return string_1;
    }
    
    public void setString_1(java.lang.String string_1) {
        this.string_1 = string_1;
    }
    
    public java.lang.String getString_2() {
        return string_2;
    }
    
    public void setString_2(java.lang.String string_2) {
        this.string_2 = string_2;
    }
}
